spring.application.name=Meal-Dash
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=create

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT}
mealDash.backend.base.url=http://localhost:8085

keycloak.server-url=http://localhost:8091
realm=mealDash
keycloak.auth.user=${KEYCLOAK_USERNAME}
keycloak.auth.password=${KEYCLOAK_PASSWORD}
keycloak.client-id=${CLIENT_ID}
jwt.auth.converter.principal-attribute=preferred_username
keycloak.client-secret=${CLIENT_SECRET}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.server-url}/realms/${realm}
spring.security.oauth2.resourceserver.opaquetoken.client-id=mealDash
spring.security.oauth2.resourceserver.opaquetoken.client-secret=${CLIENT_SECRET}
spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=${keycloak.server-url}/realms/${realm}/protocol/openid-connect/token/introspect
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.server-url}/realms/${realm}/protocol/openid-connect/certs
logging.level.org.springframework.security=DEBUG
keycloak.refresh-token.url=${keycloak.server-url}/realms/${realm}/protocol/openid-connect/token

sendgrid.api-key=${SEND_GRID_API_KEY}


