spring.profiles.active=${PROFILE:local}

spring.application.name=Meal-Dash
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/postgres}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8085}

keycloak.server-url=http://localhost:8091
realm=MealDash
keycloak.auth.user=admin
keycloak.auth.password=admin
keycloak.client-id=MealDash
jwt.auth.converter.principal-attribute=preferred_username
keycloak.client-secret=fdZsX9tJ2naK9rBUCutB3luW1C0ADQvq
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.server-url}/realms/${realm}

